services:
  jenkins:
    build:
      context: ./jenkins
    container_name: projet-devops-jenkins
    user: "0:0"
    ports:
      - "8081:8080"
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc.yaml
      JENKINS_ADMIN_USER: admin
      JENKINS_ADMIN_PASSWORD: admin
      JENKINS_URL: http://localhost:8081/
      STUDENT_NAME: NomPrenom
      GIT_REPO_URL: https://github.com/MORS4/devops.git
      GIT_BRANCH: "*/main"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/casc.yaml:/var/jenkins_home/casc.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:

